name: Build Python Development Executables

on:
    push:
        paths:
            - '**.py'
            - 'requirements.txt'
            - '.github/workflows/development-build.yml'

jobs:
    build-windows:
        runs-on: windows-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
            
            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                python-version: '3.12'
            
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt
                pip install pyinstaller

            - name: Build executable
              run: pyinstaller --onefile --add-data "app/services/configurators/templates:templates" run.py

            - name: Upload Windows artifact
              uses: actions/upload-artifact@v4
              with:
                name: python-windows-executable
                path: dist/run.exe

    build-macos:
        runs-on: macos-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
            
            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                python-version: '3.12'
            
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt
                pip install pyinstaller

            - name: Build executable
              run: pyinstaller --onefile --add-data "app/services/configurators/templates:templates" run.py

            - name: Upload Windows artifact
              uses: actions/upload-artifact@v4
              with:
                name: python-macos-executable
                path: dist/run

    build-linux:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
            
            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                python-version: '3.12'
            
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt
                pip install pyinstaller

            - name: Build executable
              run: pyinstaller --onefile --add-data "app/services/configurators/templates:templates" run.py

            - name: Upload Windows artifact
              uses: actions/upload-artifact@v4
              with:
                name: python-linux-executable
                path: dist/run